; =====================================================================
; LabVIEW Vibration Monitoring Project Configuration
; =====================================================================

[Diagnostic_Modes]
; Determines which operational profile section below is actively parsed
Selected_Mode = "Basic_Health"

[System_Settings]
; Global Hardware Bypass Toggle
; True  = Disconnects NI-DAQmx and executes internal software wave simulation
; False = Connects directly to the physical NI MAX tasks for live data acquisition
Simulation_Mode = True

; Simulation Engine Profiles
; Dictates which specific fault scenario vector to generate inside your simulation HAL
; Options: 
; Healthy "0", Unbalance_Alert "1", Bearing_Fault_Critical "2", Sweep_Test "3"
Sim_Profile = "1"


; =====================================================================
; Hardware Task & Digitizer Configurations
; =====================================================================

[Basic_Health]
Task_Name = "Basic_Health_Task"
Sample_Rate_Hz = 2000.0
Samples_Per_Channel = 1000

[Complex_Machinery]
Task_Name = "3_Axis_Analysis_Task"
Sample_Rate_Hz = 51200.0
Samples_Per_Channel = 1024

[Multi_Point]
Task_Name = "Multi_Point_Task"
Sample_Rate_Hz = 25600.0
Samples_Per_Channel = 2048