; =====================================================================
; LabVIEW Vibration Monitoring Project Configuration
; =====================================================================

[Diagnostic_Modes]
; Determines which operational profile section below is actively parsed
Selected_Mode = "Multi_Point"

[System_Settings]
; Global Hardware Bypass Toggle
; True  = Disconnects NI-DAQmx and executes internal software wave simulation
; False = Connects directly to the physical NI MAX tasks for live data acquisition
Simulation_Mode = True

; Simulation Engine Profiles
; Dictates which specific fault scenario vector to generate inside your simulation HAL
; Options: 
; Healthy "0", Unbalance_Alert "1", Bearing_Fault_Critical "2", Sweep_Test "3"
Sim_Profile = "0"


; =====================================================================
; Hardware Task & Digitizer Configurations
; =====================================================================

[Basic_Health]
Task_Name = "Local_Basic_Health_Task"
Sample_Rate_Hz = 2000.0
Samples_Per_Channel = 1024
RPM_Task_Name = "Local_RPM_Task"
RPM_PPR = 1.0

[Complex_Machinery]
Task_Name = "Local_3_Axis_Analysis_Task"
Sample_Rate_Hz = 2000.0
Samples_Per_Channel = 1024
RPM_Task_Name = "Local_RPM_Task"
RPM_PPR = 60.0

[Multi_Point]
Task_Name = "Local_Multi_Point_Task"
Sample_Rate_Hz = 2000
Samples_Per_Channel = 2048
RPM_Task_Name = "Local_RPM_Task"
RPM_PPR = 1.0

[Relay]
Task_Name = "Local_Trip_Relay_Task"


; ==============================================================================
; Tachometer / RPM Counter Configuration
; ==============================================================================
[RPM]
Task_Name = "Local_RPM_Task"
Pulses_Per_Rev = 1.0
Max_Expected_RPM = 6000.0
Min_Expected_RPM = 60.0
Terminal_Name = "PFI9"
